# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "hxreborn"
repo = "punch-hole-download-progress"

[changelog]
header = ""
body = """
{%- macro remote_url() -%}
https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- macro commit(commit) -%}
- [{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}) \
  {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
  {{ commit.message | upper_first | trim }}\
  {% if commit.breaking %} [**breaking**]{% endif %}\
  {% if commit.remote.username %} by @{{ commit.remote.username }}\
  {%- if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}){% endif %}{% endif %}
{%- if commit.body %}

{{ commit.body | indent(prefix="  > ", first=true, blank=true) }}
{%- endif %}
{%- for footer in commit.footers %}
{%- if footer.token != "Signed-off-by" and footer.token != "Co-authored-by" %}

  > {{ footer.token }}{{ footer.separator }}{{ footer.value }}
{%- endif %}
{%- endfor %}
{% endmacro -%}

{%- if version %}
## What's Changed in [{{ version }}]({{ self::remote_url() }}/releases/tag/{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
{%- else %}
## What's Changed
{%- endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
{{ self::commit(commit=commit) }}
{%- endfor -%}
{% for commit in commits %}
{%- if not commit.scope %}
{{ self::commit(commit=commit) }}
{%- endif -%}
{%- endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
### New Contributors
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
* @{{ contributor.username }} made their first contribution\
{%- if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor %}
{%- endif %}
"""
footer = ""
trim = false
postprocessors = [
    { pattern = ' +\n', replace = "\n" },
]

[git]
conventional_commits = true
filter_unconventional = true
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
commit_parsers = [
  { message = "^feat", group = "<!-- 00 -->Features" },
  { message = "^[fF]ix", group = "<!-- 01 -->Bug Fixes" },
  { message = "^refactor|^style", group = "<!-- 02 -->Refactor" },
  { message = "^doc", group = "<!-- 03 -->Documentation" },
  { message = "^perf", group = "<!-- 04 -->Performance Improvements" },
  { message = "^test", group = "<!-- 05 -->Testing" },
  { message = "^chore\\(release\\)|^chore\\(deps\\)|^chore\\(changelog\\)", skip = true },
  { message = "^[cC]hore", group = "<!-- 06 -->Miscellaneous" },
  { message = "^build", group = "<!-- 07 -->Build" },
  { body = ".*[Ss]ecurity", group = "<!-- 08 -->Security" },
  { message = "^ci", skip = true },
  { message = "^revert", group = "<!-- 09 -->Reverted" },
]
filter_commits = false
tag_pattern = "v[0-9]*"
# skip_tags = "beta|alpha"
topo_order = false
sort_commits = "newest"
